version: 2
jobs:
  build:
    docker:
      - image: devdemisto/content-build:3.0.0.3368  # disable-secrets-detection
    resource_class: medium+
    environment:
      CONTENT_VERSION: "20.2.2"
      SERVER_VERSION: "5.0.1"
      GIT_SHA1: "d1b27ef528c416fd9c10b8fa0233970f174d88ea" # guardrails-disable-line disable-secrets-detection
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Prepare Environment
          when: always
          command: |
              if [ -n "${INSTANCE_TESTS}" ] && [ $CIRCLE_NODE_INDEX -ne 0 ] ;
                then
                  echo "Skipping - instance tests tasks are running only in container number 0"
                  exit 0
              fi
              echo 'export CIRCLE_ARTIFACTS="/home/circleci/project/artifacts"' >> $BASH_ENV
              echo 'export PATH="/home/circleci/.local/bin:${PATH}"' >> $BASH_ENV # disable-secrets-detection
              echo 'export PYTHONPATH="/home/circleci/project:${PYTHONPATH}"' >> $BASH_ENV
              echo "=== sourcing $BASH_ENV ==="
              source $BASH_ENV
              sudo mkdir -p -m 777 $CIRCLE_ARTIFACTS
              chmod +x ./Tests/scripts/*
              chmod +x ./Tests/lastest_server_build_scripts/*
              echo "Parameters: NIGHTLY: $NIGHTLY, NON_AMI_RUN: $NON_AMI_RUN, SERVER_BRANCH_NAME: $SERVER_BRANCH_NAME, INSTANCE_TESTS: $INSTANCE_TESTS"
              if [ ! -e "venv" ]; then
                echo "installing venv"
                NO_HOOKS=1 .hooks/bootstrap
                source ./venv/bin/activate
                pip install -r .circleci/build-requirements.txt
                pip3 install -r .circleci/build-requirements.txt
              else
                echo "venv exists (from cache). activating"
                source ./venv/bin/activate
              fi
              # store in bash env so we load our venv in each step
              echo 'source /home/circleci/project/venv/bin/activate' >> $BASH_ENV
              python --version
              python3 --version
      - add_ssh_keys:
          fingerprints:
              - "02:df:a5:6a:53:9a:f5:5d:bd:a6:fc:b2:db:9b:c9:47" # disable-secrets-detection
              - "f5:25:6a:e5:ac:4b:84:fb:60:54:14:82:f1:e9:6c:f9" # disable-secrets-detection
      - run:
          name: Run Unit Testing and Lint
          when: always
          command: |
            demisto-sdk lint -a --disable-progress-bar -p 5 -r ./artifacts/
      - store_artifacts:
          path: artifacts
          destination: artifacts

workflows:
  version: 2
  commit:
    jobs:
      - build
