#!/bin/bash

# prevent push to master
if [ -z "$1"  ]; then
    protected_branch='master'
    current_branch=$(git symbolic-ref HEAD | sed -e 's,.*/\(.*\),\1,')
    if [ $protected_branch = $current_branch ]; then
        echo "pushing to master is not allowed"
        exit 1
    fi
fi

echo ""
