#!/bin/bash

# validating that each modified file has a valid schema, release notes, proper prefix & suffix
echo "Validating files..."
DO_DEACTIVATE=""
DO_ACTIVATE=""
if [[ -n "${VIRTUAL_ENV}" && "${VIRTUAL_ENV}" != "${PWD}/venv" && -e "${VIRTUAL_ENV}/bin/activate" ]] && command -v deactivate >/dev/null 2>&1; then
    # we are in a vritual env. Deactivate and store the previous VIRTUAL_ENV
    echo "Deactivating current virtual env: $VIRTUAL_ENV"
    DO_ACTIVATE="${VIRTUAL_ENV}"
    deactivate
fi
if [ -e "./venv/bin/activate" -a -z "${VIRTUAL_ENV}" ]; then
    echo "Activating Demisto Content virtual env..."
    source ./venv/bin/activate
    DO_DEACTIVATE=1
fi

demisto-sdk validate --post-commit
RES=$?

demisto-sdk secrets --post-commit --ignore-entropy
RES=$(($RES + $?))

echo ""
echo "Running content dev tasks (flake8, mypy, bandit, pylint, pytest)"
demisto-sdk lint -g -p
RES=$(($RES + $?))


if [ -n "$DO_DEACTIVATE" ]; then
    echo "Deactivating Demisto Content virtual env..."
    deactivate
fi
if [ -n "$DO_ACTIVATE" ]; then
    echo "Activating back previous virtual env: $DO_ACTIVATE"
    source "${DO_ACTIVATE}/bin/activate"
fi
if [[ $RES -ne 0 ]]
  then
    echo "Please fix the aforementioned errors and then commit again"
    exit 1
fi

